apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  strategy:
    blueGreen:
      activeService: guestbook-ui-svc
      autoPromotionEnabled: true
      prePromotionAnalysis:
        templates:
          - templateName: curl-vote
      previewService: guestbook-preview-svc
  template:
    spec:
      replicas: 1
      revisionHistoryLimit: 3
      selector:
        matchLabels:
          app: guestbook-ui
      template:
        metadata:
          labels:
            app: guestbook-ui
        spec:
          containers:
          - image: ks-guestbook-demo
            name: guestbook-ui
            ports:
            - containerPort: 80
