namePrefix: kustomize-

images:
- name: ks-guestbook-demo
  newName: salesdemocf/guestbook
  newTag: fail

resources:
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
