namePrefix: kustomize-

resources:
- guestbook-rollout.yaml
- guestbook-ui-preview-svc.yaml
- guestbook-ui-svc.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

openapi:
  path: https://raw.githubusercontent.com/argoproj/argo-schema-generator/main/schema/argo_all_k8s_kustomize_schema.json

patches:
- patch: |-
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    metadata:
      name: guestbook-ui
    spec:
      template:
        spec:
          template:
            spec:
              containers:
              - name: guestbook
                image: salesdemocf/guestbook:502a9e6558ce96dd88ae796ecd99cf0ac53d6cd1