result:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/result
    tag: "pr-19-update-cats-to-birds-71f299d"
vote:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/vote
    tag: "pr-20-update-dogs-to-cats-1656fbb"
worker:
  image:
    repository: codedev.jfrog.io/poc-demo-1-docker-local/worker
    tag: stable
